<?php

use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Product::create([
            'producto'=>'leche',
            'unidad_id'=>'2',
            'familia_id'=>'1',
            'limite'=>'30',
            'cantidad'=>'40'
        ]);
        \App\Product::create([
            'producto'=>'mantequilla',
            'unidad_id'=>'1',
            'familia_id'=>'1',
            'limite'=>'70',
            'cantidad'=>'90'
        ]);
        \App\Product::create([
            'producto'=>'queso',
            'unidad_id'=>'1',
            'familia_id'=>'1',
            'limite'=>'5',
            'cantidad'=>'10'
        ]);
        \App\Product::create([
            'producto'=>'fideos',
            'unidad_id'=>'3',
            'familia_id'=>'2',
            'limite'=>'30',
            'cantidad'=>'60'
        ]);
        \App\Product::create([
            'producto'=>'salsa tomate',
            'unidad_id'=>'1',
            'familia_id'=>'2',
            'limite'=>'40',
            'cantidad'=>'80'
        ]);
        \App\Product::create([
            'producto'=>'azucar',
            'unidad_id'=>'3',
            'familia_id'=>'2',
            'limite'=>'40',
            'cantidad'=>'80'
        ]);
        \App\Product::create([
            'producto'=>'sal',
            'unidad_id'=>'3',
            'familia_id'=>'2',
            'limite'=>'50',
            'cantidad'=>'100'
        ]);
        \App\Product::create([
            'producto'=>'carne molida',
            'unidad_id'=>'3',
            'familia_id'=>'3',
            'limite'=>'20',
            'cantidad'=>'40'
        ]);
        \App\Product::create([
            'producto'=>'cerdo',
            'unidad_id'=>'3',
            'familia_id'=>'3',
            'limite'=>'30',
            'cantidad'=>'60'
        ]);
        \App\Product::create([
            'producto'=>'vacuno',
            'unidad_id'=>'3',
            'familia_id'=>'3',
            'limite'=>'20',
            'cantidad'=>'40'
        ]);
        \App\Product::create([
            'producto'=>'ron',
            'unidad_id'=>'2',
            'familia_id'=>'4',
            'limite'=>'8',
            'cantidad'=>'16'
        ]);
        \App\Product::create([
            'producto'=>'pisco',
            'unidad_id'=>'3',
            'familia_id'=>'4',
            'limite'=>'30',
            'cantidad'=>'60'
        ]);
        \App\Product::create([
            'producto'=>'valcanes del sur',
            'unidad_id'=>'3',
            'familia_id'=>'5',
            'limite'=>'90',
            'cantidad'=>'180'
        ]);
        \App\Product::create([
            'producto'=>'escudo',
            'unidad_id'=>'3',
            'familia_id'=>'5',
            'limite'=>'80',
            'cantidad'=>'160'
        ]);
    }
}
