<?php

use Illuminate\Database\Seeder;

class RelProvProdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\RelProvProduct::create([
        'prov_id'=>'1',
        'prod_id'=>'11',
        'precio'=>'1200',
    ]);
        \App\RelProvProduct::create([
            'prov_id'=>'1',
            'prod_id'=>'12',
            'precio'=>'1500',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'1',
            'prod_id'=>'13',
            'precio'=>'900',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'1',
            'prod_id'=>'14',
            'precio'=>'800',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'1',
            'precio'=>'900',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'2',
            'precio'=>'650',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'3',
            'precio'=>'10100',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'4',
            'precio'=>'400',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'5',
            'precio'=>'600',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'6',
            'precio'=>'400',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'7',
            'precio'=>'300',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'11',
            'precio'=>'1200',
        ]);
        \App\RelProvProduct::create([
        'prov_id'=>'2',
        'prod_id'=>'12',
        'precio'=>'1300',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'13',
            'precio'=>'910',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'2',
            'prod_id'=>'14',
            'precio'=>'850',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'1',
            'precio'=>'910',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'2',
            'precio'=>'640',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'3',
            'precio'=>'1000',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'4',
            'precio'=>'500',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'5',
            'precio'=>'400',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'6',
            'precio'=>'390',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'7',
            'precio'=>'280',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'8',
            'precio'=>'2200',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'9',
            'precio'=>'3500',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'10',
            'precio'=>'3000',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'11',
            'precio'=>'1100',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'12',
            'precio'=>'900',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'3',
            'prod_id'=>'13',
            'precio'=>'700',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'4',
            'prod_id'=>'8',
            'precio'=>'2100',
        ]);
        \App\RelProvProduct::create([
            'prov_id'=>'4',
            'prod_id'=>'9',
            'precio'=>'3300',
        ]);
        \App\RelProvProduct::create([
        'prov_id'=>'4',
        'prod_id'=>'10',
        'precio'=>'3000',
        ]);
    }
}
